# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='número do pedido')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_separacao', 'Em separação'), ('pronto', 'Pronto para retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('devolvido', 'Devolvido')], db_index=True, default='rascunho', max_length=25, verbose_name='status do pedido')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto (R$)')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total (R$)')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('transferencia', 'Transferência'), ('cortesia', 'Cortesia'), ('outro', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado')], default='pendente', max_length=10, verbose_name='status do pagamento')),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da compra')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='data de retirada / entrega')),
                ('local_retirada', models.CharField(blank=True, max_length=160, verbose_name='local de retirada')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprovante', models.TextField(blank=True, max_length=100, null=True, verbose_name='comprovante')),
                ('estoque_baixado', models.BooleanField(default=False, verbose_name='estoque baixado')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'historical pedido',
                'verbose_name_plural': 'historical pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='número do pedido')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_separacao', 'Em separação'), ('pronto', 'Pronto para retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('devolvido', 'Devolvido')], db_index=True, default='rascunho', max_length=25, verbose_name='status do pedido')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto (R$)')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total (R$)')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('transferencia', 'Transferência'), ('cortesia', 'Cortesia'), ('outro', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado')], default='pendente', max_length=10, verbose_name='status do pagamento')),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da compra')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='data de retirada / entrega')),
                ('local_retirada', models.CharField(blank=True, max_length=160, verbose_name='local de retirada')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='pedidos/', verbose_name='comprovante')),
                ('estoque_baixado', models.BooleanField(default=False, verbose_name='estoque baixado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='crm.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('forma', models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('transferencia', 'Transferência'), ('cortesia', 'Cortesia'), ('outro', 'Outro')], max_length=20, verbose_name='forma')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário (R$)')),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto do item (R$)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalogo.produto', verbose_name='produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
