# Generated by Django 5.2.17 on 2026-09-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='numero',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True, verbose_name='número do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='número do pedido'),
        ),
    ]
