# Generated by Django 5.2.17 on 2026-09-09 16:50

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('festa', 'Festa'), ('jogo', 'Jogo'), ('torneio', 'Torneio / Campeonato'), ('churrasco', 'Churrasco / Resenha'), ('viagem', 'Viagem'), ('jogos_univ', 'Jogos universitários'), ('venda', 'Venda especial'), ('academico', 'Evento acadêmico'), ('outro', 'Outro')], db_index=True, default='festa', max_length=15, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('horario', models.CharField(blank=True, max_length=40, verbose_name='horário')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='local')),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade')),
                ('publico_realizado', models.PositiveIntegerField(blank=True, help_text='Preencher depois do evento, se souber o número real.', null=True, verbose_name='público (realizado)')),
                ('staff_cortesias', models.PositiveIntegerField(default=0, help_text='Pessoas que entram sem pagar (não contam como receita).', verbose_name='staff / cortesias')),
                ('status', models.CharField(choices=[('planejamento', 'Em planejamento'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='planejamento', max_length=15, verbose_name='status')),
                ('publico_alvo', models.CharField(blank=True, max_length=160, verbose_name='público-alvo')),
                ('link_inscricao', models.URLField(blank=True, verbose_name='link de inscrição / ingressos')),
                ('orcamento_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='orçamento previsto (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('demo', models.BooleanField(default=False, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('fornecedores', models.ManyToManyField(blank=True, related_name='eventos', to='fornecedores.fornecedor', verbose_name='fornecedores envolvidos')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CustoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fixo', 'Custo fixo'), ('variavel', 'Custo variável')], default='fixo', max_length=10, verbose_name='tipo')),
                ('item', models.CharField(max_length=160, verbose_name='item')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor unitário (R$)')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor já pago (R$)')),
                ('situacao', models.CharField(choices=[('pendente', 'A pagar'), ('parcial', 'Sinal pago'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='situação')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_evento', to='fornecedores.fornecedor', verbose_name='fornecedor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='eventos.evento', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'custo do evento',
                'verbose_name_plural': 'custos do evento',
                'ordering': ['tipo', 'item'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('festa', 'Festa'), ('jogo', 'Jogo'), ('torneio', 'Torneio / Campeonato'), ('churrasco', 'Churrasco / Resenha'), ('viagem', 'Viagem'), ('jogos_univ', 'Jogos universitários'), ('venda', 'Venda especial'), ('academico', 'Evento acadêmico'), ('outro', 'Outro')], db_index=True, default='festa', max_length=15, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('horario', models.CharField(blank=True, max_length=40, verbose_name='horário')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='local')),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade')),
                ('publico_realizado', models.PositiveIntegerField(blank=True, help_text='Preencher depois do evento, se souber o número real.', null=True, verbose_name='público (realizado)')),
                ('staff_cortesias', models.PositiveIntegerField(default=0, help_text='Pessoas que entram sem pagar (não contam como receita).', verbose_name='staff / cortesias')),
                ('status', models.CharField(choices=[('planejamento', 'Em planejamento'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='planejamento', max_length=15, verbose_name='status')),
                ('publico_alvo', models.CharField(blank=True, max_length=160, verbose_name='público-alvo')),
                ('link_inscricao', models.URLField(blank=True, verbose_name='link de inscrição / ingressos')),
                ('orcamento_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='orçamento previsto (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('demo', models.BooleanField(default=False, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'historical evento',
                'verbose_name_plural': 'historical eventos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoteIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='lote')),
                ('quantidade_prevista', models.PositiveIntegerField(default=0, verbose_name='qtd. prevista')),
                ('quantidade_vendida', models.PositiveIntegerField(default=0, verbose_name='qtd. vendida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor unitário (R$)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='eventos.evento', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'lote de ingresso',
                'verbose_name_plural': 'lotes de ingresso',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('bar', 'Bar / bebidas'), ('patrocinio', 'Patrocínio do evento'), ('parceria', 'Parceria'), ('outro', 'Outro')], default='outro', max_length=15, verbose_name='origem')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('recebido', models.BooleanField(default=False, verbose_name='recebido')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='eventos.evento', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'receita do evento',
                'verbose_name_plural': 'receitas do evento',
                'ordering': ['-valor'],
            },
        ),
    ]
