# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='a_fazer', max_length=15, verbose_name='status')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='tarefas/', verbose_name='anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='crm.cliente', verbose_name='cliente relacionado')),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='fornecedores.fornecedor', verbose_name='fornecedor relacionado')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='vendas.pedido', verbose_name='pedido relacionado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['status', 'prazo', '-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefa', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'comentário de tarefa',
                'verbose_name_plural': 'comentários de tarefa',
                'ordering': ['criado_em'],
            },
        ),
    ]
