# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de produto',
                'verbose_name_plural': 'categorias de produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de mercadoria'), ('saida_venda', 'Saída por venda'), ('saida_evento', 'Saída para evento'), ('saida_doacao', 'Saída por doação'), ('perda', 'Perda / avaria'), ('ajuste_pos', 'Ajuste (entrada)'), ('ajuste_neg', 'Ajuste (saída)'), ('devolucao', 'Devolução (entrada)'), ('transferencia', 'Transferência entre locais')], max_length=20, verbose_name='tipo de movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade')),
                ('saldo_apos', models.IntegerField(blank=True, null=True, verbose_name='saldo após')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('motivo', models.CharField(blank=True, max_length=160, verbose_name='motivo')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('codigo_interno', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='código interno')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='SKU')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='foto')),
                ('tamanho', models.CharField(blank=True, max_length=20, verbose_name='tamanho')),
                ('cor', models.CharField(blank=True, max_length=40, verbose_name='cor')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='marca')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo unitário (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de venda (R$)')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='quantidade em estoque')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='estoque mínimo')),
                ('estoque_maximo', models.IntegerField(blank=True, null=True, verbose_name='estoque máximo')),
                ('localizacao', models.CharField(blank=True, max_length=120, verbose_name='localização física')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('codigo_interno', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='código interno')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='SKU')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto')),
                ('tamanho', models.CharField(blank=True, max_length=20, verbose_name='tamanho')),
                ('cor', models.CharField(blank=True, max_length=40, verbose_name='cor')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='marca')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo unitário (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de venda (R$)')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='quantidade em estoque')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='estoque mínimo')),
                ('estoque_maximo', models.IntegerField(blank=True, null=True, verbose_name='estoque máximo')),
                ('localizacao', models.CharField(blank=True, max_length=120, verbose_name='localização física')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='cadastrado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.categoriaproduto', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'historical produto',
                'verbose_name_plural': 'historical produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
