# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por'),
        ),
        migrations.AddField(
            model_name='historicalproduto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fornecedores.fornecedor', verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalproduto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='vendas.pedido', verbose_name='pedido relacionado'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalogo.categoriaproduto', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_criados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fornecedores.fornecedor', verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='catalogo.produto', verbose_name='produto'),
        ),
    ]
