# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('cor', models.CharField(default='#6c757d', max_length=7, verbose_name='cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de cliente',
                'verbose_name_plural': 'categorias de cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='nome')),
                ('cor', models.CharField(default='#0d6efd', max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome completo')),
                ('nome_social', models.CharField(blank=True, max_length=160, verbose_name='nome social')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('membro_fgv', models.BooleanField(default=True, verbose_name='é da comunidade FGV?')),
                ('vinculo', models.CharField(choices=[('aluno', 'Aluno FGV'), ('ex_aluno', 'Ex-aluno'), ('funcionario', 'Funcionário FGV'), ('externo', 'Sem vínculo com a FGV'), ('outro', 'Outro')], default='aluno', max_length=20, verbose_name='tipo de vínculo')),
                ('curso', models.CharField(blank=True, max_length=120, verbose_name='curso')),
                ('periodo', models.CharField(blank=True, max_length=30, verbose_name='período')),
                ('campus', models.CharField(blank=True, max_length=120, verbose_name='campus')),
                ('turma', models.CharField(blank=True, max_length=60, verbose_name='turma')),
                ('origem', models.CharField(blank=True, max_length=120, verbose_name='origem do contato')),
                ('relacionamento', models.CharField(choices=[('novo', 'Novo contato'), ('ativo', 'Ativo'), ('recorrente', 'Recorrente'), ('inativo', 'Inativo')], default='novo', max_length=20, verbose_name='status do relacionamento')),
                ('aceita_comunicacoes', models.BooleanField(default=False, help_text='Consentimento para e-mail/WhatsApp (LGPD).', verbose_name='autoriza receber comunicações')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='crm.categoriacliente', verbose_name='categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('tags', models.ManyToManyField(blank=True, related_name='clientes', to='crm.tag')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome completo')),
                ('nome_social', models.CharField(blank=True, max_length=160, verbose_name='nome social')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('membro_fgv', models.BooleanField(default=True, verbose_name='é da comunidade FGV?')),
                ('vinculo', models.CharField(choices=[('aluno', 'Aluno FGV'), ('ex_aluno', 'Ex-aluno'), ('funcionario', 'Funcionário FGV'), ('externo', 'Sem vínculo com a FGV'), ('outro', 'Outro')], default='aluno', max_length=20, verbose_name='tipo de vínculo')),
                ('curso', models.CharField(blank=True, max_length=120, verbose_name='curso')),
                ('periodo', models.CharField(blank=True, max_length=30, verbose_name='período')),
                ('campus', models.CharField(blank=True, max_length=120, verbose_name='campus')),
                ('turma', models.CharField(blank=True, max_length=60, verbose_name='turma')),
                ('origem', models.CharField(blank=True, max_length=120, verbose_name='origem do contato')),
                ('relacionamento', models.CharField(choices=[('novo', 'Novo contato'), ('ativo', 'Ativo'), ('recorrente', 'Recorrente'), ('inativo', 'Inativo')], default='novo', max_length=20, verbose_name='status do relacionamento')),
                ('aceita_comunicacoes', models.BooleanField(default=False, help_text='Consentimento para e-mail/WhatsApp (LGPD).', verbose_name='autoriza receber comunicações')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='cadastrado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.categoriacliente', verbose_name='categoria')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cliente',
                'verbose_name_plural': 'historical clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('presencial', 'Presencial'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('resumo', models.CharField(max_length=255, verbose_name='resumo')),
                ('detalhe', models.TextField(blank=True, verbose_name='detalhe')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.cliente', verbose_name='cliente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='crm_cliente_nome_b786a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='crm_cliente_email_3bea01_idx'),
        ),
    ]
