# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='razão social ou nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=160, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CNPJ / CPF')),
                ('contato_nome', models.CharField(blank=True, max_length=120, verbose_name='pessoa de contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('categoria', models.CharField(choices=[('confeccao', 'Confecção'), ('bebidas', 'Bebidas'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('grafica', 'Gráfica'), ('eventos', 'Eventos'), ('marketing', 'Marketing'), ('tecnologia', 'Tecnologia'), ('patrocinio', 'Patrocínio'), ('servicos', 'Serviços gerais'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoria')),
                ('produtos_servicos', models.TextField(blank=True, verbose_name='produtos ou serviços fornecidos')),
                ('condicoes_comerciais', models.TextField(blank=True, verbose_name='condições comerciais')),
                ('prazo_medio_entrega', models.CharField(blank=True, max_length=60, verbose_name='prazo médio de entrega')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='status')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='fornecedores/', verbose_name='contrato / documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='preço')),
                ('qualidade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='qualidade')),
                ('prazo', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='prazo')),
                ('atendimento', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='atendimento')),
                ('confiabilidade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='confiabilidade')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_fornecedor', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='fornecedores.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'avaliação de fornecedor',
                'verbose_name_plural': 'avaliações de fornecedor',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFornecedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='razão social ou nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=160, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CNPJ / CPF')),
                ('contato_nome', models.CharField(blank=True, max_length=120, verbose_name='pessoa de contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('categoria', models.CharField(choices=[('confeccao', 'Confecção'), ('bebidas', 'Bebidas'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('grafica', 'Gráfica'), ('eventos', 'Eventos'), ('marketing', 'Marketing'), ('tecnologia', 'Tecnologia'), ('patrocinio', 'Patrocínio'), ('servicos', 'Serviços gerais'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoria')),
                ('produtos_servicos', models.TextField(blank=True, verbose_name='produtos ou serviços fornecidos')),
                ('condicoes_comerciais', models.TextField(blank=True, verbose_name='condições comerciais')),
                ('prazo_medio_entrega', models.CharField(blank=True, max_length=60, verbose_name='prazo médio de entrega')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='status')),
                ('contrato', models.TextField(blank=True, max_length=100, null=True, verbose_name='contrato / documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='cadastrado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fornecedor',
                'verbose_name_plural': 'historical fornecedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
