/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthContaRouteImport } from './routes/_auth/conta'
import { Route as AuthAdministracaoAcessosRouteImport } from './routes/_auth/administracao/acessos'
import { Route as AuthAdministracaoConfiguracaoRouteImport } from './routes/_auth/administracao/configuracao'
import { Route as AuthAdministracaoHistoricoRouteImport } from './routes/_auth/administracao/historico'
import { Route as AuthAdministracaoImportarRouteImport } from './routes/_auth/administracao/importar'
import { Route as AuthAdministracaoMembrosRouteImport } from './routes/_auth/administracao/membros'
import { Route as AuthAdministracaoSheetsRouteImport } from './routes/_auth/administracao/sheets'
import { Route as AuthClientesIndexRouteImport } from './routes/_auth/clientes/index'
import { Route as AuthClientesNovoRouteImport } from './routes/_auth/clientes/novo'
import { Route as AuthEventosIndexRouteImport } from './routes/_auth/eventos/index'
import { Route as AuthEventosNovoRouteImport } from './routes/_auth/eventos/novo'
import { Route as AuthFornecedoresIndexRouteImport } from './routes/_auth/fornecedores/index'
import { Route as AuthFornecedoresNovoRouteImport } from './routes/_auth/fornecedores/novo'
import { Route as AuthPedidosIndexRouteImport } from './routes/_auth/pedidos/index'
import { Route as AuthPedidosNovoRouteImport } from './routes/_auth/pedidos/novo'
import { Route as AuthProdutosIndexRouteImport } from './routes/_auth/produtos/index'
import { Route as AuthProdutosMovimentacoesRouteImport } from './routes/_auth/produtos/movimentacoes'
import { Route as AuthProdutosNovoRouteImport } from './routes/_auth/produtos/novo'
import { Route as AuthRelatoriosIndexRouteImport } from './routes/_auth/relatorios/index'
import { Route as AuthRelatoriosClientesRouteImport } from './routes/_auth/relatorios/clientes'
import { Route as AuthRelatoriosEstoqueRouteImport } from './routes/_auth/relatorios/estoque'
import { Route as AuthRelatoriosProdutosRouteImport } from './routes/_auth/relatorios/produtos'
import { Route as AuthRelatoriosVendasRouteImport } from './routes/_auth/relatorios/vendas'
import { Route as AuthTarefasIndexRouteImport } from './routes/_auth/tarefas/index'
import { Route as AuthTarefasListaRouteImport } from './routes/_auth/tarefas/lista'
import { Route as AuthTarefasNovaRouteImport } from './routes/_auth/tarefas/nova'
import { Route as AuthClientesIdIndexRouteImport } from './routes/_auth/clientes/$id/index'
import { Route as AuthClientesIdEditarRouteImport } from './routes/_auth/clientes/$id/editar'
import { Route as AuthEventosIdIndexRouteImport } from './routes/_auth/eventos/$id/index'
import { Route as AuthEventosIdEditarRouteImport } from './routes/_auth/eventos/$id/editar'
import { Route as AuthFornecedoresIdIndexRouteImport } from './routes/_auth/fornecedores/$id/index'
import { Route as AuthFornecedoresIdEditarRouteImport } from './routes/_auth/fornecedores/$id/editar'
import { Route as AuthPedidosIdIndexRouteImport } from './routes/_auth/pedidos/$id/index'
import { Route as AuthPedidosIdEditarRouteImport } from './routes/_auth/pedidos/$id/editar'
import { Route as AuthProdutosIdIndexRouteImport } from './routes/_auth/produtos/$id/index'
import { Route as AuthProdutosIdEditarRouteImport } from './routes/_auth/produtos/$id/editar'
import { Route as AuthTarefasIdIndexRouteImport } from './routes/_auth/tarefas/$id/index'
import { Route as AuthTarefasIdEditarRouteImport } from './routes/_auth/tarefas/$id/editar'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContaRoute = AuthContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdministracaoAcessosRoute =
  AuthAdministracaoAcessosRouteImport.update({
    id: '/administracao/acessos',
    path: '/administracao/acessos',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministracaoConfiguracaoRoute =
  AuthAdministracaoConfiguracaoRouteImport.update({
    id: '/administracao/configuracao',
    path: '/administracao/configuracao',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministracaoHistoricoRoute =
  AuthAdministracaoHistoricoRouteImport.update({
    id: '/administracao/historico',
    path: '/administracao/historico',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministracaoImportarRoute =
  AuthAdministracaoImportarRouteImport.update({
    id: '/administracao/importar',
    path: '/administracao/importar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministracaoMembrosRoute =
  AuthAdministracaoMembrosRouteImport.update({
    id: '/administracao/membros',
    path: '/administracao/membros',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministracaoSheetsRoute = AuthAdministracaoSheetsRouteImport.update({
  id: '/administracao/sheets',
  path: '/administracao/sheets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesIndexRoute = AuthClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesNovoRoute = AuthClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventosIndexRoute = AuthEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventosNovoRoute = AuthEventosNovoRouteImport.update({
  id: '/eventos/novo',
  path: '/eventos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFornecedoresIndexRoute = AuthFornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFornecedoresNovoRoute = AuthFornecedoresNovoRouteImport.update({
  id: '/fornecedores/novo',
  path: '/fornecedores/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPedidosIndexRoute = AuthPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPedidosNovoRoute = AuthPedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProdutosIndexRoute = AuthProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProdutosMovimentacoesRoute =
  AuthProdutosMovimentacoesRouteImport.update({
    id: '/produtos/movimentacoes',
    path: '/produtos/movimentacoes',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProdutosNovoRoute = AuthProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosIndexRoute = AuthRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosClientesRoute = AuthRelatoriosClientesRouteImport.update({
  id: '/relatorios/clientes',
  path: '/relatorios/clientes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosEstoqueRoute = AuthRelatoriosEstoqueRouteImport.update({
  id: '/relatorios/estoque',
  path: '/relatorios/estoque',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosProdutosRoute = AuthRelatoriosProdutosRouteImport.update({
  id: '/relatorios/produtos',
  path: '/relatorios/produtos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosVendasRoute = AuthRelatoriosVendasRouteImport.update({
  id: '/relatorios/vendas',
  path: '/relatorios/vendas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTarefasIndexRoute = AuthTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTarefasListaRoute = AuthTarefasListaRouteImport.update({
  id: '/tarefas/lista',
  path: '/tarefas/lista',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTarefasNovaRoute = AuthTarefasNovaRouteImport.update({
  id: '/tarefas/nova',
  path: '/tarefas/nova',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesIdIndexRoute = AuthClientesIdIndexRouteImport.update({
  id: '/clientes/$id/',
  path: '/clientes/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesIdEditarRoute = AuthClientesIdEditarRouteImport.update({
  id: '/clientes/$id/editar',
  path: '/clientes/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventosIdIndexRoute = AuthEventosIdIndexRouteImport.update({
  id: '/eventos/$id/',
  path: '/eventos/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventosIdEditarRoute = AuthEventosIdEditarRouteImport.update({
  id: '/eventos/$id/editar',
  path: '/eventos/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFornecedoresIdIndexRoute = AuthFornecedoresIdIndexRouteImport.update({
  id: '/fornecedores/$id/',
  path: '/fornecedores/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFornecedoresIdEditarRoute =
  AuthFornecedoresIdEditarRouteImport.update({
    id: '/fornecedores/$id/editar',
    path: '/fornecedores/$id/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPedidosIdIndexRoute = AuthPedidosIdIndexRouteImport.update({
  id: '/pedidos/$id/',
  path: '/pedidos/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPedidosIdEditarRoute = AuthPedidosIdEditarRouteImport.update({
  id: '/pedidos/$id/editar',
  path: '/pedidos/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProdutosIdIndexRoute = AuthProdutosIdIndexRouteImport.update({
  id: '/produtos/$id/',
  path: '/produtos/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProdutosIdEditarRoute = AuthProdutosIdEditarRouteImport.update({
  id: '/produtos/$id/editar',
  path: '/produtos/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTarefasIdIndexRoute = AuthTarefasIdIndexRouteImport.update({
  id: '/tarefas/$id/',
  path: '/tarefas/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTarefasIdEditarRoute = AuthTarefasIdEditarRouteImport.update({
  id: '/tarefas/$id/editar',
  path: '/tarefas/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/conta': typeof AuthContaRoute
  '/administracao/acessos': typeof AuthAdministracaoAcessosRoute
  '/administracao/configuracao': typeof AuthAdministracaoConfiguracaoRoute
  '/administracao/historico': typeof AuthAdministracaoHistoricoRoute
  '/administracao/importar': typeof AuthAdministracaoImportarRoute
  '/administracao/membros': typeof AuthAdministracaoMembrosRoute
  '/administracao/sheets': typeof AuthAdministracaoSheetsRoute
  '/clientes/novo': typeof AuthClientesNovoRoute
  '/eventos/novo': typeof AuthEventosNovoRoute
  '/fornecedores/novo': typeof AuthFornecedoresNovoRoute
  '/pedidos/novo': typeof AuthPedidosNovoRoute
  '/produtos/movimentacoes': typeof AuthProdutosMovimentacoesRoute
  '/produtos/novo': typeof AuthProdutosNovoRoute
  '/relatorios/clientes': typeof AuthRelatoriosClientesRoute
  '/relatorios/estoque': typeof AuthRelatoriosEstoqueRoute
  '/relatorios/produtos': typeof AuthRelatoriosProdutosRoute
  '/relatorios/vendas': typeof AuthRelatoriosVendasRoute
  '/tarefas/lista': typeof AuthTarefasListaRoute
  '/tarefas/nova': typeof AuthTarefasNovaRoute
  '/clientes/': typeof AuthClientesIndexRoute
  '/eventos/': typeof AuthEventosIndexRoute
  '/fornecedores/': typeof AuthFornecedoresIndexRoute
  '/pedidos/': typeof AuthPedidosIndexRoute
  '/produtos/': typeof AuthProdutosIndexRoute
  '/relatorios/': typeof AuthRelatoriosIndexRoute
  '/tarefas/': typeof AuthTarefasIndexRoute
  '/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/eventos/$id/editar': typeof AuthEventosIdEditarRoute
  '/fornecedores/$id/editar': typeof AuthFornecedoresIdEditarRoute
  '/pedidos/$id/editar': typeof AuthPedidosIdEditarRoute
  '/produtos/$id/editar': typeof AuthProdutosIdEditarRoute
  '/tarefas/$id/editar': typeof AuthTarefasIdEditarRoute
  '/clientes/$id/': typeof AuthClientesIdIndexRoute
  '/eventos/$id/': typeof AuthEventosIdIndexRoute
  '/fornecedores/$id/': typeof AuthFornecedoresIdIndexRoute
  '/pedidos/$id/': typeof AuthPedidosIdIndexRoute
  '/produtos/$id/': typeof AuthProdutosIdIndexRoute
  '/tarefas/$id/': typeof AuthTarefasIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/conta': typeof AuthContaRoute
  '/': typeof AuthIndexRoute
  '/administracao/acessos': typeof AuthAdministracaoAcessosRoute
  '/administracao/configuracao': typeof AuthAdministracaoConfiguracaoRoute
  '/administracao/historico': typeof AuthAdministracaoHistoricoRoute
  '/administracao/importar': typeof AuthAdministracaoImportarRoute
  '/administracao/membros': typeof AuthAdministracaoMembrosRoute
  '/administracao/sheets': typeof AuthAdministracaoSheetsRoute
  '/clientes/novo': typeof AuthClientesNovoRoute
  '/eventos/novo': typeof AuthEventosNovoRoute
  '/fornecedores/novo': typeof AuthFornecedoresNovoRoute
  '/pedidos/novo': typeof AuthPedidosNovoRoute
  '/produtos/movimentacoes': typeof AuthProdutosMovimentacoesRoute
  '/produtos/novo': typeof AuthProdutosNovoRoute
  '/relatorios/clientes': typeof AuthRelatoriosClientesRoute
  '/relatorios/estoque': typeof AuthRelatoriosEstoqueRoute
  '/relatorios/produtos': typeof AuthRelatoriosProdutosRoute
  '/relatorios/vendas': typeof AuthRelatoriosVendasRoute
  '/tarefas/lista': typeof AuthTarefasListaRoute
  '/tarefas/nova': typeof AuthTarefasNovaRoute
  '/clientes': typeof AuthClientesIndexRoute
  '/eventos': typeof AuthEventosIndexRoute
  '/fornecedores': typeof AuthFornecedoresIndexRoute
  '/pedidos': typeof AuthPedidosIndexRoute
  '/produtos': typeof AuthProdutosIndexRoute
  '/relatorios': typeof AuthRelatoriosIndexRoute
  '/tarefas': typeof AuthTarefasIndexRoute
  '/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/eventos/$id/editar': typeof AuthEventosIdEditarRoute
  '/fornecedores/$id/editar': typeof AuthFornecedoresIdEditarRoute
  '/pedidos/$id/editar': typeof AuthPedidosIdEditarRoute
  '/produtos/$id/editar': typeof AuthProdutosIdEditarRoute
  '/tarefas/$id/editar': typeof AuthTarefasIdEditarRoute
  '/clientes/$id': typeof AuthClientesIdIndexRoute
  '/eventos/$id': typeof AuthEventosIdIndexRoute
  '/fornecedores/$id': typeof AuthFornecedoresIdIndexRoute
  '/pedidos/$id': typeof AuthPedidosIdIndexRoute
  '/produtos/$id': typeof AuthProdutosIdIndexRoute
  '/tarefas/$id': typeof AuthTarefasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/conta': typeof AuthContaRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/administracao/acessos': typeof AuthAdministracaoAcessosRoute
  '/_auth/administracao/configuracao': typeof AuthAdministracaoConfiguracaoRoute
  '/_auth/administracao/historico': typeof AuthAdministracaoHistoricoRoute
  '/_auth/administracao/importar': typeof AuthAdministracaoImportarRoute
  '/_auth/administracao/membros': typeof AuthAdministracaoMembrosRoute
  '/_auth/administracao/sheets': typeof AuthAdministracaoSheetsRoute
  '/_auth/clientes/novo': typeof AuthClientesNovoRoute
  '/_auth/eventos/novo': typeof AuthEventosNovoRoute
  '/_auth/fornecedores/novo': typeof AuthFornecedoresNovoRoute
  '/_auth/pedidos/novo': typeof AuthPedidosNovoRoute
  '/_auth/produtos/movimentacoes': typeof AuthProdutosMovimentacoesRoute
  '/_auth/produtos/novo': typeof AuthProdutosNovoRoute
  '/_auth/relatorios/clientes': typeof AuthRelatoriosClientesRoute
  '/_auth/relatorios/estoque': typeof AuthRelatoriosEstoqueRoute
  '/_auth/relatorios/produtos': typeof AuthRelatoriosProdutosRoute
  '/_auth/relatorios/vendas': typeof AuthRelatoriosVendasRoute
  '/_auth/tarefas/lista': typeof AuthTarefasListaRoute
  '/_auth/tarefas/nova': typeof AuthTarefasNovaRoute
  '/_auth/clientes/': typeof AuthClientesIndexRoute
  '/_auth/eventos/': typeof AuthEventosIndexRoute
  '/_auth/fornecedores/': typeof AuthFornecedoresIndexRoute
  '/_auth/pedidos/': typeof AuthPedidosIndexRoute
  '/_auth/produtos/': typeof AuthProdutosIndexRoute
  '/_auth/relatorios/': typeof AuthRelatoriosIndexRoute
  '/_auth/tarefas/': typeof AuthTarefasIndexRoute
  '/_auth/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/_auth/eventos/$id/editar': typeof AuthEventosIdEditarRoute
  '/_auth/fornecedores/$id/editar': typeof AuthFornecedoresIdEditarRoute
  '/_auth/pedidos/$id/editar': typeof AuthPedidosIdEditarRoute
  '/_auth/produtos/$id/editar': typeof AuthProdutosIdEditarRoute
  '/_auth/tarefas/$id/editar': typeof AuthTarefasIdEditarRoute
  '/_auth/clientes/$id/': typeof AuthClientesIdIndexRoute
  '/_auth/eventos/$id/': typeof AuthEventosIdIndexRoute
  '/_auth/fornecedores/$id/': typeof AuthFornecedoresIdIndexRoute
  '/_auth/pedidos/$id/': typeof AuthPedidosIdIndexRoute
  '/_auth/produtos/$id/': typeof AuthProdutosIdIndexRoute
  '/_auth/tarefas/$id/': typeof AuthTarefasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conta'
    | '/administracao/acessos'
    | '/administracao/configuracao'
    | '/administracao/historico'
    | '/administracao/importar'
    | '/administracao/membros'
    | '/administracao/sheets'
    | '/clientes/novo'
    | '/eventos/novo'
    | '/fornecedores/novo'
    | '/pedidos/novo'
    | '/produtos/movimentacoes'
    | '/produtos/novo'
    | '/relatorios/clientes'
    | '/relatorios/estoque'
    | '/relatorios/produtos'
    | '/relatorios/vendas'
    | '/tarefas/lista'
    | '/tarefas/nova'
    | '/clientes/'
    | '/eventos/'
    | '/fornecedores/'
    | '/pedidos/'
    | '/produtos/'
    | '/relatorios/'
    | '/tarefas/'
    | '/clientes/$id/editar'
    | '/eventos/$id/editar'
    | '/fornecedores/$id/editar'
    | '/pedidos/$id/editar'
    | '/produtos/$id/editar'
    | '/tarefas/$id/editar'
    | '/clientes/$id/'
    | '/eventos/$id/'
    | '/fornecedores/$id/'
    | '/pedidos/$id/'
    | '/produtos/$id/'
    | '/tarefas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/conta'
    | '/'
    | '/administracao/acessos'
    | '/administracao/configuracao'
    | '/administracao/historico'
    | '/administracao/importar'
    | '/administracao/membros'
    | '/administracao/sheets'
    | '/clientes/novo'
    | '/eventos/novo'
    | '/fornecedores/novo'
    | '/pedidos/novo'
    | '/produtos/movimentacoes'
    | '/produtos/novo'
    | '/relatorios/clientes'
    | '/relatorios/estoque'
    | '/relatorios/produtos'
    | '/relatorios/vendas'
    | '/tarefas/lista'
    | '/tarefas/nova'
    | '/clientes'
    | '/eventos'
    | '/fornecedores'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/tarefas'
    | '/clientes/$id/editar'
    | '/eventos/$id/editar'
    | '/fornecedores/$id/editar'
    | '/pedidos/$id/editar'
    | '/produtos/$id/editar'
    | '/tarefas/$id/editar'
    | '/clientes/$id'
    | '/eventos/$id'
    | '/fornecedores/$id'
    | '/pedidos/$id'
    | '/produtos/$id'
    | '/tarefas/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/conta'
    | '/_auth/'
    | '/_auth/administracao/acessos'
    | '/_auth/administracao/configuracao'
    | '/_auth/administracao/historico'
    | '/_auth/administracao/importar'
    | '/_auth/administracao/membros'
    | '/_auth/administracao/sheets'
    | '/_auth/clientes/novo'
    | '/_auth/eventos/novo'
    | '/_auth/fornecedores/novo'
    | '/_auth/pedidos/novo'
    | '/_auth/produtos/movimentacoes'
    | '/_auth/produtos/novo'
    | '/_auth/relatorios/clientes'
    | '/_auth/relatorios/estoque'
    | '/_auth/relatorios/produtos'
    | '/_auth/relatorios/vendas'
    | '/_auth/tarefas/lista'
    | '/_auth/tarefas/nova'
    | '/_auth/clientes/'
    | '/_auth/eventos/'
    | '/_auth/fornecedores/'
    | '/_auth/pedidos/'
    | '/_auth/produtos/'
    | '/_auth/relatorios/'
    | '/_auth/tarefas/'
    | '/_auth/clientes/$id/editar'
    | '/_auth/eventos/$id/editar'
    | '/_auth/fornecedores/$id/editar'
    | '/_auth/pedidos/$id/editar'
    | '/_auth/produtos/$id/editar'
    | '/_auth/tarefas/$id/editar'
    | '/_auth/clientes/$id/'
    | '/_auth/eventos/$id/'
    | '/_auth/fornecedores/$id/'
    | '/_auth/pedidos/$id/'
    | '/_auth/produtos/$id/'
    | '/_auth/tarefas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conta': {
      id: '/_auth/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthContaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/acessos': {
      id: '/_auth/administracao/acessos'
      path: '/administracao/acessos'
      fullPath: '/administracao/acessos'
      preLoaderRoute: typeof AuthAdministracaoAcessosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/configuracao': {
      id: '/_auth/administracao/configuracao'
      path: '/administracao/configuracao'
      fullPath: '/administracao/configuracao'
      preLoaderRoute: typeof AuthAdministracaoConfiguracaoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/historico': {
      id: '/_auth/administracao/historico'
      path: '/administracao/historico'
      fullPath: '/administracao/historico'
      preLoaderRoute: typeof AuthAdministracaoHistoricoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/importar': {
      id: '/_auth/administracao/importar'
      path: '/administracao/importar'
      fullPath: '/administracao/importar'
      preLoaderRoute: typeof AuthAdministracaoImportarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/membros': {
      id: '/_auth/administracao/membros'
      path: '/administracao/membros'
      fullPath: '/administracao/membros'
      preLoaderRoute: typeof AuthAdministracaoMembrosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administracao/sheets': {
      id: '/_auth/administracao/sheets'
      path: '/administracao/sheets'
      fullPath: '/administracao/sheets'
      preLoaderRoute: typeof AuthAdministracaoSheetsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/': {
      id: '/_auth/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthClientesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/novo': {
      id: '/_auth/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthClientesNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eventos/': {
      id: '/_auth/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthEventosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eventos/novo': {
      id: '/_auth/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof AuthEventosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fornecedores/': {
      id: '/_auth/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof AuthFornecedoresIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fornecedores/novo': {
      id: '/_auth/fornecedores/novo'
      path: '/fornecedores/novo'
      fullPath: '/fornecedores/novo'
      preLoaderRoute: typeof AuthFornecedoresNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pedidos/': {
      id: '/_auth/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthPedidosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pedidos/novo': {
      id: '/_auth/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthPedidosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produtos/': {
      id: '/_auth/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthProdutosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produtos/movimentacoes': {
      id: '/_auth/produtos/movimentacoes'
      path: '/produtos/movimentacoes'
      fullPath: '/produtos/movimentacoes'
      preLoaderRoute: typeof AuthProdutosMovimentacoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produtos/novo': {
      id: '/_auth/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthProdutosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/': {
      id: '/_auth/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthRelatoriosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/clientes': {
      id: '/_auth/relatorios/clientes'
      path: '/relatorios/clientes'
      fullPath: '/relatorios/clientes'
      preLoaderRoute: typeof AuthRelatoriosClientesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/estoque': {
      id: '/_auth/relatorios/estoque'
      path: '/relatorios/estoque'
      fullPath: '/relatorios/estoque'
      preLoaderRoute: typeof AuthRelatoriosEstoqueRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/produtos': {
      id: '/_auth/relatorios/produtos'
      path: '/relatorios/produtos'
      fullPath: '/relatorios/produtos'
      preLoaderRoute: typeof AuthRelatoriosProdutosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/vendas': {
      id: '/_auth/relatorios/vendas'
      path: '/relatorios/vendas'
      fullPath: '/relatorios/vendas'
      preLoaderRoute: typeof AuthRelatoriosVendasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tarefas/': {
      id: '/_auth/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AuthTarefasIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tarefas/lista': {
      id: '/_auth/tarefas/lista'
      path: '/tarefas/lista'
      fullPath: '/tarefas/lista'
      preLoaderRoute: typeof AuthTarefasListaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tarefas/nova': {
      id: '/_auth/tarefas/nova'
      path: '/tarefas/nova'
      fullPath: '/tarefas/nova'
      preLoaderRoute: typeof AuthTarefasNovaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/$id/': {
      id: '/_auth/clientes/$id/'
      path: '/clientes/$id'
      fullPath: '/clientes/$id/'
      preLoaderRoute: typeof AuthClientesIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/$id/editar': {
      id: '/_auth/clientes/$id/editar'
      path: '/clientes/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthClientesIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eventos/$id/': {
      id: '/_auth/eventos/$id/'
      path: '/eventos/$id'
      fullPath: '/eventos/$id/'
      preLoaderRoute: typeof AuthEventosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eventos/$id/editar': {
      id: '/_auth/eventos/$id/editar'
      path: '/eventos/$id/editar'
      fullPath: '/eventos/$id/editar'
      preLoaderRoute: typeof AuthEventosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fornecedores/$id/': {
      id: '/_auth/fornecedores/$id/'
      path: '/fornecedores/$id'
      fullPath: '/fornecedores/$id/'
      preLoaderRoute: typeof AuthFornecedoresIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fornecedores/$id/editar': {
      id: '/_auth/fornecedores/$id/editar'
      path: '/fornecedores/$id/editar'
      fullPath: '/fornecedores/$id/editar'
      preLoaderRoute: typeof AuthFornecedoresIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pedidos/$id/': {
      id: '/_auth/pedidos/$id/'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id/'
      preLoaderRoute: typeof AuthPedidosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pedidos/$id/editar': {
      id: '/_auth/pedidos/$id/editar'
      path: '/pedidos/$id/editar'
      fullPath: '/pedidos/$id/editar'
      preLoaderRoute: typeof AuthPedidosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produtos/$id/': {
      id: '/_auth/produtos/$id/'
      path: '/produtos/$id'
      fullPath: '/produtos/$id/'
      preLoaderRoute: typeof AuthProdutosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produtos/$id/editar': {
      id: '/_auth/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/produtos/$id/editar'
      preLoaderRoute: typeof AuthProdutosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tarefas/$id/': {
      id: '/_auth/tarefas/$id/'
      path: '/tarefas/$id'
      fullPath: '/tarefas/$id/'
      preLoaderRoute: typeof AuthTarefasIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tarefas/$id/editar': {
      id: '/_auth/tarefas/$id/editar'
      path: '/tarefas/$id/editar'
      fullPath: '/tarefas/$id/editar'
      preLoaderRoute: typeof AuthTarefasIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthContaRoute: typeof AuthContaRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdministracaoAcessosRoute: typeof AuthAdministracaoAcessosRoute
  AuthAdministracaoConfiguracaoRoute: typeof AuthAdministracaoConfiguracaoRoute
  AuthAdministracaoHistoricoRoute: typeof AuthAdministracaoHistoricoRoute
  AuthAdministracaoImportarRoute: typeof AuthAdministracaoImportarRoute
  AuthAdministracaoMembrosRoute: typeof AuthAdministracaoMembrosRoute
  AuthAdministracaoSheetsRoute: typeof AuthAdministracaoSheetsRoute
  AuthClientesNovoRoute: typeof AuthClientesNovoRoute
  AuthEventosNovoRoute: typeof AuthEventosNovoRoute
  AuthFornecedoresNovoRoute: typeof AuthFornecedoresNovoRoute
  AuthPedidosNovoRoute: typeof AuthPedidosNovoRoute
  AuthProdutosMovimentacoesRoute: typeof AuthProdutosMovimentacoesRoute
  AuthProdutosNovoRoute: typeof AuthProdutosNovoRoute
  AuthRelatoriosClientesRoute: typeof AuthRelatoriosClientesRoute
  AuthRelatoriosEstoqueRoute: typeof AuthRelatoriosEstoqueRoute
  AuthRelatoriosProdutosRoute: typeof AuthRelatoriosProdutosRoute
  AuthRelatoriosVendasRoute: typeof AuthRelatoriosVendasRoute
  AuthTarefasListaRoute: typeof AuthTarefasListaRoute
  AuthTarefasNovaRoute: typeof AuthTarefasNovaRoute
  AuthClientesIndexRoute: typeof AuthClientesIndexRoute
  AuthEventosIndexRoute: typeof AuthEventosIndexRoute
  AuthFornecedoresIndexRoute: typeof AuthFornecedoresIndexRoute
  AuthPedidosIndexRoute: typeof AuthPedidosIndexRoute
  AuthProdutosIndexRoute: typeof AuthProdutosIndexRoute
  AuthRelatoriosIndexRoute: typeof AuthRelatoriosIndexRoute
  AuthTarefasIndexRoute: typeof AuthTarefasIndexRoute
  AuthClientesIdEditarRoute: typeof AuthClientesIdEditarRoute
  AuthEventosIdEditarRoute: typeof AuthEventosIdEditarRoute
  AuthFornecedoresIdEditarRoute: typeof AuthFornecedoresIdEditarRoute
  AuthPedidosIdEditarRoute: typeof AuthPedidosIdEditarRoute
  AuthProdutosIdEditarRoute: typeof AuthProdutosIdEditarRoute
  AuthTarefasIdEditarRoute: typeof AuthTarefasIdEditarRoute
  AuthClientesIdIndexRoute: typeof AuthClientesIdIndexRoute
  AuthEventosIdIndexRoute: typeof AuthEventosIdIndexRoute
  AuthFornecedoresIdIndexRoute: typeof AuthFornecedoresIdIndexRoute
  AuthPedidosIdIndexRoute: typeof AuthPedidosIdIndexRoute
  AuthProdutosIdIndexRoute: typeof AuthProdutosIdIndexRoute
  AuthTarefasIdIndexRoute: typeof AuthTarefasIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthContaRoute: AuthContaRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdministracaoAcessosRoute: AuthAdministracaoAcessosRoute,
  AuthAdministracaoConfiguracaoRoute: AuthAdministracaoConfiguracaoRoute,
  AuthAdministracaoHistoricoRoute: AuthAdministracaoHistoricoRoute,
  AuthAdministracaoImportarRoute: AuthAdministracaoImportarRoute,
  AuthAdministracaoMembrosRoute: AuthAdministracaoMembrosRoute,
  AuthAdministracaoSheetsRoute: AuthAdministracaoSheetsRoute,
  AuthClientesNovoRoute: AuthClientesNovoRoute,
  AuthEventosNovoRoute: AuthEventosNovoRoute,
  AuthFornecedoresNovoRoute: AuthFornecedoresNovoRoute,
  AuthPedidosNovoRoute: AuthPedidosNovoRoute,
  AuthProdutosMovimentacoesRoute: AuthProdutosMovimentacoesRoute,
  AuthProdutosNovoRoute: AuthProdutosNovoRoute,
  AuthRelatoriosClientesRoute: AuthRelatoriosClientesRoute,
  AuthRelatoriosEstoqueRoute: AuthRelatoriosEstoqueRoute,
  AuthRelatoriosProdutosRoute: AuthRelatoriosProdutosRoute,
  AuthRelatoriosVendasRoute: AuthRelatoriosVendasRoute,
  AuthTarefasListaRoute: AuthTarefasListaRoute,
  AuthTarefasNovaRoute: AuthTarefasNovaRoute,
  AuthClientesIndexRoute: AuthClientesIndexRoute,
  AuthEventosIndexRoute: AuthEventosIndexRoute,
  AuthFornecedoresIndexRoute: AuthFornecedoresIndexRoute,
  AuthPedidosIndexRoute: AuthPedidosIndexRoute,
  AuthProdutosIndexRoute: AuthProdutosIndexRoute,
  AuthRelatoriosIndexRoute: AuthRelatoriosIndexRoute,
  AuthTarefasIndexRoute: AuthTarefasIndexRoute,
  AuthClientesIdEditarRoute: AuthClientesIdEditarRoute,
  AuthEventosIdEditarRoute: AuthEventosIdEditarRoute,
  AuthFornecedoresIdEditarRoute: AuthFornecedoresIdEditarRoute,
  AuthPedidosIdEditarRoute: AuthPedidosIdEditarRoute,
  AuthProdutosIdEditarRoute: AuthProdutosIdEditarRoute,
  AuthTarefasIdEditarRoute: AuthTarefasIdEditarRoute,
  AuthClientesIdIndexRoute: AuthClientesIdIndexRoute,
  AuthEventosIdIndexRoute: AuthEventosIdIndexRoute,
  AuthFornecedoresIdIndexRoute: AuthFornecedoresIdIndexRoute,
  AuthPedidosIdIndexRoute: AuthPedidosIdIndexRoute,
  AuthProdutosIdIndexRoute: AuthProdutosIdIndexRoute,
  AuthTarefasIdIndexRoute: AuthTarefasIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
