# Generated by Django 5.2.17 on 2026-09-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizacao', models.CharField(default='Atlética FGV Rio', max_length=120, verbose_name='nome da organização')),
                ('titulo_app', models.CharField(default='CRM Atlética', max_length=120, verbose_name='título da aplicação')),
                ('sobre', models.TextField(blank=True, verbose_name='informações institucionais')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='identidade/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='identidade/', verbose_name='favicon')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='identidade/', verbose_name='imagem de capa / banner')),
                ('cor_primaria', models.CharField(default='#1B2A4A', max_length=7, verbose_name='cor primária')),
                ('cor_secundaria', models.CharField(default='#F4B400', max_length=7, verbose_name='cor secundária')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=40, verbose_name='telefone de contato')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('instagram', models.CharField(blank=True, max_length=120, verbose_name='Instagram')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('modo_escuro_disponivel', models.BooleanField(default=False, verbose_name='disponibilizar modo escuro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('agente', models.CharField(blank=True, max_length=255, verbose_name='navegador / dispositivo')),
                ('sucesso', models.BooleanField(default=True, verbose_name='acesso bem-sucedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de acesso',
                'verbose_name_plural': 'logs de acesso',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40, verbose_name='ação')),
                ('alvo', models.CharField(blank=True, max_length=160, verbose_name='registro afetado')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de atividade',
                'verbose_name_plural': 'registros de atividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
