# Generated by Django 5.2.17 on 2026-09-17 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_marca_gorilada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FontePlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('planilha', models.CharField(help_text='Cole a URL do Google Sheets. O ID e a aba saem dela.', max_length=255, verbose_name='planilha (URL ou ID)')),
                ('aba', models.CharField(blank=True, help_text='Em branco usa a aba indicada na URL colada, ou a primeira.', max_length=120, verbose_name='aba')),
                ('destino', models.CharField(choices=[('clientes', 'Clientes'), ('fornecedores', 'Fornecedores / Parceiros'), ('controle_produtos', 'Controle de Produtos')], max_length=30, verbose_name='importar como')),
                ('modo', models.CharField(choices=[('criar_atualizar', 'Criar e completar os que já existem'), ('somente_criar', 'Somente criar novos')], default='criar_atualizar', max_length=20, verbose_name='modo')),
                ('ativa', models.BooleanField(default=True, verbose_name='sincronizar automaticamente')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('ultimo_resultado', models.CharField(blank=True, max_length=255, verbose_name='último resultado')),
                ('ultimo_erro', models.CharField(blank=True, max_length=255, verbose_name='último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrada em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_planilha', to=settings.AUTH_USER_MODEL, verbose_name='cadastrada por')),
            ],
            options={
                'verbose_name': 'fonte de planilha',
                'verbose_name_plural': 'fontes de planilha',
                'ordering': ['nome'],
            },
        ),
    ]
